#pragma once
#include <avalon/macro/n_args.hpp>

#define AVALON_CONCATE(     a, b        )     a##b
// #define AVALON_FOREACH_ONE( f, elem     )     f(elem)
#define AVALON_FOREACH_(    f, n, ...   )     AVALON_CONCATE(  AVALON_FOREACH_, n )(f, __VA_ARGS__)
#define AVALON_FOREACH(     f, ...      )     AVALON_FOREACH_( f, AVALON_N_ARGS(__VA_ARGS__), __VA_ARGS__ )

#define AVALON_FOREACH_64( f, elem, ... )     f(elem) AVALON_FOREACH_63(f, __VA_ARGS__)
#define AVALON_FOREACH_63( f, elem, ... )     f(elem) AVALON_FOREACH_62(f, __VA_ARGS__)
#define AVALON_FOREACH_62( f, elem, ... )     f(elem) AVALON_FOREACH_61(f, __VA_ARGS__)
#define AVALON_FOREACH_61( f, elem, ... )     f(elem) AVALON_FOREACH_60(f, __VA_ARGS__)
#define AVALON_FOREACH_60( f, elem, ... )     f(elem) AVALON_FOREACH_59(f, __VA_ARGS__)
#define AVALON_FOREACH_59( f, elem, ... )     f(elem) AVALON_FOREACH_58(f, __VA_ARGS__)
#define AVALON_FOREACH_58( f, elem, ... )     f(elem) AVALON_FOREACH_57(f, __VA_ARGS__)
#define AVALON_FOREACH_57( f, elem, ... )     f(elem) AVALON_FOREACH_56(f, __VA_ARGS__)
#define AVALON_FOREACH_56( f, elem, ... )     f(elem) AVALON_FOREACH_55(f, __VA_ARGS__)
#define AVALON_FOREACH_55( f, elem, ... )     f(elem) AVALON_FOREACH_54(f, __VA_ARGS__)
#define AVALON_FOREACH_54( f, elem, ... )     f(elem) AVALON_FOREACH_53(f, __VA_ARGS__)
#define AVALON_FOREACH_53( f, elem, ... )     f(elem) AVALON_FOREACH_52(f, __VA_ARGS__)
#define AVALON_FOREACH_52( f, elem, ... )     f(elem) AVALON_FOREACH_51(f, __VA_ARGS__)
#define AVALON_FOREACH_51( f, elem, ... )     f(elem) AVALON_FOREACH_50(f, __VA_ARGS__)
#define AVALON_FOREACH_50( f, elem, ... )     f(elem) AVALON_FOREACH_49(f, __VA_ARGS__)
#define AVALON_FOREACH_49( f, elem, ... )     f(elem) AVALON_FOREACH_48(f, __VA_ARGS__)
#define AVALON_FOREACH_48( f, elem, ... )     f(elem) AVALON_FOREACH_47(f, __VA_ARGS__)
#define AVALON_FOREACH_47( f, elem, ... )     f(elem) AVALON_FOREACH_46(f, __VA_ARGS__)
#define AVALON_FOREACH_46( f, elem, ... )     f(elem) AVALON_FOREACH_45(f, __VA_ARGS__)
#define AVALON_FOREACH_45( f, elem, ... )     f(elem) AVALON_FOREACH_44(f, __VA_ARGS__)
#define AVALON_FOREACH_44( f, elem, ... )     f(elem) AVALON_FOREACH_43(f, __VA_ARGS__)
#define AVALON_FOREACH_43( f, elem, ... )     f(elem) AVALON_FOREACH_42(f, __VA_ARGS__)
#define AVALON_FOREACH_42( f, elem, ... )     f(elem) AVALON_FOREACH_41(f, __VA_ARGS__)
#define AVALON_FOREACH_41( f, elem, ... )     f(elem) AVALON_FOREACH_40(f, __VA_ARGS__)
#define AVALON_FOREACH_40( f, elem, ... )     f(elem) AVALON_FOREACH_39(f, __VA_ARGS__)
#define AVALON_FOREACH_39( f, elem, ... )     f(elem) AVALON_FOREACH_38(f, __VA_ARGS__)
#define AVALON_FOREACH_38( f, elem, ... )     f(elem) AVALON_FOREACH_37(f, __VA_ARGS__)
#define AVALON_FOREACH_37( f, elem, ... )     f(elem) AVALON_FOREACH_36(f, __VA_ARGS__)
#define AVALON_FOREACH_36( f, elem, ... )     f(elem) AVALON_FOREACH_35(f, __VA_ARGS__)
#define AVALON_FOREACH_35( f, elem, ... )     f(elem) AVALON_FOREACH_34(f, __VA_ARGS__)
#define AVALON_FOREACH_34( f, elem, ... )     f(elem) AVALON_FOREACH_33(f, __VA_ARGS__)
#define AVALON_FOREACH_33( f, elem, ... )     f(elem) AVALON_FOREACH_32(f, __VA_ARGS__)
#define AVALON_FOREACH_32( f, elem, ... )     f(elem) AVALON_FOREACH_31(f, __VA_ARGS__)
#define AVALON_FOREACH_31( f, elem, ... )     f(elem) AVALON_FOREACH_30(f, __VA_ARGS__)
#define AVALON_FOREACH_30( f, elem, ... )     f(elem) AVALON_FOREACH_29(f, __VA_ARGS__)
#define AVALON_FOREACH_29( f, elem, ... )     f(elem) AVALON_FOREACH_28(f, __VA_ARGS__)
#define AVALON_FOREACH_28( f, elem, ... )     f(elem) AVALON_FOREACH_27(f, __VA_ARGS__)
#define AVALON_FOREACH_27( f, elem, ... )     f(elem) AVALON_FOREACH_26(f, __VA_ARGS__)
#define AVALON_FOREACH_26( f, elem, ... )     f(elem) AVALON_FOREACH_25(f, __VA_ARGS__)
#define AVALON_FOREACH_25( f, elem, ... )     f(elem) AVALON_FOREACH_24(f, __VA_ARGS__)
#define AVALON_FOREACH_24( f, elem, ... )     f(elem) AVALON_FOREACH_23(f, __VA_ARGS__)
#define AVALON_FOREACH_23( f, elem, ... )     f(elem) AVALON_FOREACH_22(f, __VA_ARGS__)
#define AVALON_FOREACH_22( f, elem, ... )     f(elem) AVALON_FOREACH_21(f, __VA_ARGS__)
#define AVALON_FOREACH_21( f, elem, ... )     f(elem) AVALON_FOREACH_20(f, __VA_ARGS__)
#define AVALON_FOREACH_20( f, elem, ... )     f(elem) AVALON_FOREACH_19(f, __VA_ARGS__)
#define AVALON_FOREACH_19( f, elem, ... )     f(elem) AVALON_FOREACH_18(f, __VA_ARGS__)
#define AVALON_FOREACH_18( f, elem, ... )     f(elem) AVALON_FOREACH_17(f, __VA_ARGS__)
#define AVALON_FOREACH_17( f, elem, ... )     f(elem) AVALON_FOREACH_16(f, __VA_ARGS__)
#define AVALON_FOREACH_16( f, elem, ... )     f(elem) AVALON_FOREACH_15(f, __VA_ARGS__)
#define AVALON_FOREACH_15( f, elem, ... )     f(elem) AVALON_FOREACH_14(f, __VA_ARGS__)
#define AVALON_FOREACH_14( f, elem, ... )     f(elem) AVALON_FOREACH_13(f, __VA_ARGS__)
#define AVALON_FOREACH_13( f, elem, ... )     f(elem) AVALON_FOREACH_12(f, __VA_ARGS__)
#define AVALON_FOREACH_12( f, elem, ... )     f(elem) AVALON_FOREACH_11(f, __VA_ARGS__)
#define AVALON_FOREACH_11( f, elem, ... )     f(elem) AVALON_FOREACH_10(f, __VA_ARGS__)
#define AVALON_FOREACH_10( f, elem, ... )     f(elem) AVALON_FOREACH_9( f, __VA_ARGS__)
#define AVALON_FOREACH_9(  f, elem, ... )     f(elem) AVALON_FOREACH_8( f, __VA_ARGS__)
#define AVALON_FOREACH_8(  f, elem, ... )     f(elem) AVALON_FOREACH_7( f, __VA_ARGS__)
#define AVALON_FOREACH_7(  f, elem, ... )     f(elem) AVALON_FOREACH_6( f, __VA_ARGS__)
#define AVALON_FOREACH_6(  f, elem, ... )     f(elem) AVALON_FOREACH_5( f, __VA_ARGS__)
#define AVALON_FOREACH_5(  f, elem, ... )     f(elem) AVALON_FOREACH_4( f, __VA_ARGS__)
#define AVALON_FOREACH_4(  f, elem, ... )     f(elem) AVALON_FOREACH_3( f, __VA_ARGS__)
#define AVALON_FOREACH_3(  f, elem, ... )     f(elem) AVALON_FOREACH_2( f, __VA_ARGS__)
#define AVALON_FOREACH_2(  f, elem, ... )     f(elem) AVALON_FOREACH_1( f, __VA_ARGS__)
#define AVALON_FOREACH_1(  f, elem )          f(elem)



#define AVALON_CTX_FOREACH_(    f, ctx, n, ...   )     AVALON_CONCATE(  AVALON_CTX_FOREACH_, n )(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH(     f, ctx, ...      )     AVALON_CTX_FOREACH_( f, ctx, AVALON_N_ARGS(__VA_ARGS__), __VA_ARGS__ )

#define AVALON_CTX_FOREACH_64( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_63(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_63( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_62(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_62( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_61(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_61( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_60(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_60( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_59(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_59( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_58(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_58( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_57(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_57( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_56(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_56( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_55(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_55( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_54(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_54( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_53(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_53( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_52(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_52( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_51(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_51( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_50(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_50( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_49(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_49( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_48(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_48( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_47(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_47( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_46(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_46( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_45(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_45( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_44(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_44( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_43(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_43( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_42(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_42( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_41(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_41( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_40(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_40( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_39(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_39( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_38(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_38( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_37(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_37( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_36(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_36( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_35(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_35( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_34(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_34( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_33(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_33( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_32(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_32( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_31(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_31( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_30(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_30( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_29(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_29( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_28(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_28( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_27(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_27( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_26(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_26( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_25(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_25( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_24(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_24( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_23(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_23( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_22(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_22( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_21(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_21( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_20(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_20( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_19(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_19( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_18(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_18( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_17(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_17( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_16(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_16( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_15(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_15( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_14(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_14( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_13(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_13( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_12(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_12( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_11(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_11( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_10(f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_10( f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_9( f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_9(  f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_8( f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_8(  f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_7( f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_7(  f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_6( f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_6(  f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_5( f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_5(  f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_4( f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_4(  f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_3( f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_3(  f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_2( f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_2(  f, ctx, elem, ... )     f(ctx, elem) AVALON_CTX_FOREACH_1( f, ctx, __VA_ARGS__)
#define AVALON_CTX_FOREACH_1(  f, ctx, elem )          f(ctx, elem)