hunter_add_package(Arkitekto)
find_package(Arkitekto CONFIG REQUIRED)
if(BUILD_TEST)
    hunter_add_package(GTest)
    find_package(GTest CONFIG REQUIRED)
endif()
hunter_add_package(fmt)
find_package(fmt CONFIG REQUIRED)

hunter_add_package(range-v3)
find_package(range-v3 CONFIG REQUIRED)

if(USE_SQLITE)
    hunter_add_package(sqlite3)
    find_package(sqlite3 CONFIG REQUIRED)
endif()
if(USE_PGSQL)
    hunter_add_package(ZLIB)
    find_package(ZLIB CONFIG REQUIRED)
    hunter_add_package(PostgreSQL)
    find_package(PostgreSQL REQUIRED)
endif()
find_package(Threads REQUIRED)